# Generated by Django 4.0.5 on 2022-07-04 09:10

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_movieprofile_cast_remove_movieprofile_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieprofile',
            name='cast',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
        migrations.AddField(
            model_name='movieprofile',
            name='crew',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
        migrations.AddField(
            model_name='movieprofile',
            name='releaseDate',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='movieprofile',
            name='reviews',
            field=jsonfield.fields.JSONField(default='[]'),
        ),
        migrations.AddField(
            model_name='movieprofile',
            name='synopsis',
            field=models.TextField(null=True),
        ),
    ]
