# Generated by Django 4.0.6 on 2022-07-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_movieprofile_cast_and_crew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posterPath', models.TextField()),
                ('releaseDate', models.TextField(null=True)),
                ('cast_and_crew', models.JSONField(default=dict)),
            ],
        ),
    ]
