# Generated by Django 4.0.5 on 2022-07-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posterPath', models.TextField()),
                ('releaseDate', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
