# Generated by Django 4.0.5 on 2022-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movie_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.TextField(default='None'),
        ),
    ]
