# Generated by Django 4.0.5 on 2022-07-04 08:54

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('posterPath', models.TextField()),
                ('releaseDate', models.TextField()),
                ('synopsis', models.TextField()),
                ('reviews', jsonfield.fields.JSONField(default='[]')),
                ('cast', jsonfield.fields.JSONField(default='[]')),
                ('crew', jsonfield.fields.JSONField(default='[]')),
            ],
        ),
    ]
