# Generated by Django 4.0.5 on 2022-07-04 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_movieprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieprofile',
            name='releaseDate',
        ),
    ]
