# Generated by Django 4.0.5 on 2022-07-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movieprofile_releasedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieprofile',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movieprofile',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='movieprofile',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='movieprofile',
            name='synopsis',
        ),
    ]
